FROM debian:trixie

# renovate: datasource=github-releases depName=tofuutils/tenv
ENV TENV_VERSION=v4.9.3

RUN apt update && apt install -y \
    git \
    python3 \
    python3-pip \
    ansible \
    curl \
    locales-all \
    && rm -rf /var/lib/apt/lists/*

RUN curl -O -L "https://github.com/tofuutils/tenv/releases/download/${TENV_VERSION}/tenv_${TENV_VERSION}_amd64.deb" \
    && dpkg -i "tenv_${TENV_VERSION}_amd64.deb" \
    && rm "tenv_${TENV_VERSION}_amd64.deb"
