FROM debian:trixie

# renovate: datasource=github-releases depName=tofuutils/tenv
ENV TENV_VERSION=v4.9.3 \
# renovate: datasource=gitlab-releases depName=gitlab-org/cli
    GITLAB_CLI_VERSION=v1.89.0 \
# renovate: datasource=github-releases depName=junegunn/fzf
    FZF_VERSION=v0.70.0

RUN apt update && apt install -y \
    git \
    python3 \
    python3-pip \
    ansible \
    curl \
    locales-all \
    jq \
    yq \
    gnupg \
    vim \
    tmux \
    ksshaskpass \
    zsh \
    && rm -rf /var/lib/apt/lists/*

RUN curl -O -L "https://github.com/tofuutils/tenv/releases/download/${TENV_VERSION}/tenv_${TENV_VERSION}_amd64.deb" \
    && dpkg -i "tenv_${TENV_VERSION}_amd64.deb" \
    && rm "tenv_${TENV_VERSION}_amd64.deb"

RUN curl -sS https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list \
    && apt update && apt install -y packer \
    && rm -rf /var/lib/apt/lists/*

RUN curl -O -L "https://gitlab.com/gitlab-org/cli/-/releases/${GITLAB_CLI_VERSION}/downloads/glab_${GITLAB_CLI_VERSION#v}_linux_amd64.deb" \
    && dpkg -i "glab_${GITLAB_CLI_VERSION#v}_linux_amd64.deb" \
    && rm "glab_${GITLAB_CLI_VERSION#v}_linux_amd64.deb"

RUN curl -O -L "https://github.com/junegunn/fzf/releases/download/${FZF_VERSION}/fzf-${FZF_VERSION#v}-linux_amd64.tar.gz" \
    && tar -xzf "fzf-${FZF_VERSION#v}-linux_amd64.tar.gz" -C /usr/local/bin \
    && rm "fzf-${FZF_VERSION#v}-linux_amd64.tar.gz"